package session

import (
	"crypto/subtle"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/saiaathish/picogent/internal/llm"
	"github.com/saiaathish/picogent/internal/securefile"
)

const (
	deleteUndoFileName      = ".delete-undo"
	deleteUndoStageFileName = ".delete-undo.stage"
	maxDeleteUndoBytes      = MaxSessionBytes + 4<<10
	maxDeleteUndoIDBytes    = 256
)

// ErrDeleteUndoNotCurrent means a caller tried to act on a recovery record
// that has been superseded by another deletion or was already retired.
var ErrDeleteUndoNotCurrent = errors.New("delete undo is no longer current")

// DeleteUndo is the short-lived, durable recovery record for one deleted
// session. It is deliberately separate from listable session JSON files, so
// a deleted chat cannot reappear in a history list before the user chooses
// Undo. The token is an opaque, local-only capability generated by the GUI.
type DeleteUndo struct {
	UndoID     string    `json:"undo_id"`
	Session    *Session  `json:"session"`
	Workspace  string    `json:"workspace"`
	WasCurrent bool      `json:"was_current"`
	ExpiresAt  time.Time `json:"expires_at"`
}

// DeleteWithUndo stages a durable recovery record before removing a session.
// A later CommitDeleteUndo makes that stage the current undo record only after
// the GUI has safely rotated away from the deleted chat. This preserves an
// earlier undo when a later deletion fails during rotation, while still making
// a crash between deletion and rotation recoverable on the next process.
func DeleteWithUndo(id string, undo *DeleteUndo) error {
	id = strings.TrimSuffix(strings.TrimSpace(id), ".json")
	if !validID(id) {
		return errors.New("invalid session id")
	}
	data, prepared, err := marshalDeleteUndo(undo)
	if err != nil {
		return err
	}
	if prepared.Session.ID != id {
		return errors.New("delete undo session id mismatch")
	}
	dir, err := Dir()
	if err != nil {
		return err
	}
	if err := securefile.EnsureDir(dir, 0o700); err != nil {
		return err
	}
	unlock, err := acquireSessionsLock(dir)
	if err != nil {
		return err
	}
	defer unlock()

	stage := deleteUndoStagePath(dir)
	if err := securefile.WriteAtomic(stage, data, 0o600); err != nil {
		return fmt.Errorf("stage delete undo: %w", err)
	}
	if err := securefile.RemoveFile(filepath.Join(dir, id+".json")); err != nil {
		cleanupErr := removeDeleteUndoFileLocked(stage)
		if cleanupErr != nil {
			return fmt.Errorf("delete session: %w; clear undo staging: %v", err, cleanupErr)
		}
		return err
	}
	return nil
}

// CommitDeleteUndo promotes a staged deletion after the caller has completed
// its session/runtime transition. If promotion fails, the stage remains a
// valid crash-recovery record and LoadDeleteUndo continues to prefer it.
func CommitDeleteUndo(undoID string) error {
	dir, err := Dir()
	if err != nil {
		return err
	}
	if err := securefile.EnsureDir(dir, 0o700); err != nil {
		return err
	}
	unlock, err := acquireSessionsLock(dir)
	if err != nil {
		return err
	}
	defer unlock()

	staged, data, err := loadDeleteUndoFileLocked(deleteUndoStagePath(dir))
	if err != nil {
		return err
	}
	if staged.UndoID != undoID {
		return errors.New("delete undo stage does not match")
	}
	if err := securefile.WriteAtomic(deleteUndoPath(dir), data, 0o600); err != nil {
		return fmt.Errorf("commit delete undo: %w", err)
	}
	return removeDeleteUndoFileLocked(deleteUndoStagePath(dir))
}

// AbortDeleteUndo clears only the currently staged delete. It intentionally
// leaves a previously committed undo record untouched.
func AbortDeleteUndo(undoID string) error {
	dir, err := Dir()
	if err != nil {
		return err
	}
	if err := securefile.EnsureDir(dir, 0o700); err != nil {
		return err
	}
	unlock, err := acquireSessionsLock(dir)
	if err != nil {
		return err
	}
	defer unlock()

	staged, _, err := loadDeleteUndoFileLocked(deleteUndoStagePath(dir))
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if staged.UndoID != undoID {
		return errors.New("delete undo stage does not match")
	}
	return removeDeleteUndoFileLocked(deleteUndoStagePath(dir))
}

// LoadDeleteUndo returns the latest usable recovery record. A staged record
// wins when its session file is absent: that is the crash boundary between a
// durable delete and GUI lifecycle publication. Expired or already-restored
// records are retired without reviving an older undo.
func LoadDeleteUndo() (*DeleteUndo, error) {
	dir, err := Dir()
	if err != nil {
		return nil, err
	}
	if err := securefile.EnsureDir(dir, 0o700); err != nil {
		return nil, err
	}
	unlock, err := acquireSessionsLock(dir)
	if err != nil {
		return nil, err
	}
	defer unlock()
	return loadCurrentDeleteUndoLocked(dir, time.Now().UTC())
}

// RestoreDeleteUndo restores and retires the current matching delete journal
// while holding the session lock. Keeping the check, restore, and retirement
// together prevents another Picogent process from replacing the journal
// between a GUI's token check and its recovery write.
//
// If restoration succeeds but journal retirement fails, the restored record is
// returned alongside the error so callers can accurately report that the chat
// came back but cleanup needs retrying.
func RestoreDeleteUndo(undoID string) (*DeleteUndo, error) {
	dir, err := Dir()
	if err != nil {
		return nil, err
	}
	if err := securefile.EnsureDir(dir, 0o700); err != nil {
		return nil, err
	}
	unlock, err := acquireSessionsLock(dir)
	if err != nil {
		return nil, err
	}
	defer unlock()

	pending, err := loadCurrentDeleteUndoLocked(dir, time.Now().UTC())
	if err != nil {
		return nil, err
	}
	if !deleteUndoIDMatches(pending.UndoID, undoID) {
		return nil, ErrDeleteUndoNotCurrent
	}
	missing, err := undoSessionMissingLocked(dir, pending.Session.ID)
	if err != nil {
		return nil, err
	}
	if !missing {
		return nil, os.ErrExist
	}
	restored := cloneDeleteUndo(pending)
	path := filepath.Join(dir, restored.Session.ID+".json")
	if restored.Session.Updated.IsZero() {
		restored.Session.Updated = time.Now().UTC()
	}
	if err := saveLocked(path, restored.Session); err != nil {
		return nil, err
	}
	if err := clearDeleteUndoLocked(dir); err != nil {
		return restored, fmt.Errorf("retire delete undo: %w", err)
	}
	return restored, nil
}

// ClearDeleteUndoIfCurrent retires a journal only if its opaque token still
// names the active delete. A stale GUI process therefore cannot erase a newer
// process's recovery record while handling expiry or a failed restore.
func ClearDeleteUndoIfCurrent(undoID string) (bool, error) {
	dir, err := Dir()
	if err != nil {
		return false, err
	}
	if err := securefile.EnsureDir(dir, 0o700); err != nil {
		return false, err
	}
	unlock, err := acquireSessionsLock(dir)
	if err != nil {
		return false, err
	}
	defer unlock()

	pending, err := loadCurrentDeleteUndoLocked(dir, time.Now().UTC())
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !deleteUndoIDMatches(pending.UndoID, undoID) {
		return false, nil
	}
	if err := clearDeleteUndoLocked(dir); err != nil {
		return false, err
	}
	return true, nil
}

func loadCurrentDeleteUndoLocked(dir string, now time.Time) (*DeleteUndo, error) {

	stagePath := deleteUndoStagePath(dir)
	staged, _, stageErr := loadDeleteUndoFileLocked(stagePath)
	if stageErr != nil && !os.IsNotExist(stageErr) {
		return nil, stageErr
	}
	if staged != nil {
		missing, err := undoSessionMissingLocked(dir, staged.Session.ID)
		if err != nil {
			return nil, err
		}
		if !missing {
			if err := removeDeleteUndoFileLocked(stagePath); err != nil {
				return nil, err
			}
		} else if deleteUndoExpired(staged, now) {
			if err := clearDeleteUndoLocked(dir); err != nil {
				return nil, err
			}
			return nil, os.ErrNotExist
		} else {
			return cloneDeleteUndo(staged), nil
		}
	}

	pending, _, err := loadDeleteUndoFileLocked(deleteUndoPath(dir))
	if err != nil {
		return nil, err
	}
	missing, err := undoSessionMissingLocked(dir, pending.Session.ID)
	if err != nil {
		return nil, err
	}
	if !missing || deleteUndoExpired(pending, now) {
		if err := clearDeleteUndoLocked(dir); err != nil {
			return nil, err
		}
		return nil, os.ErrNotExist
	}
	return cloneDeleteUndo(pending), nil
}

// ClearDeleteUndo irreversibly removes the current short-lived delete journal.
// It is idempotent so callers can retire it after successful undo, expiry, or
// rollback without turning already-cleared state into an error.
func ClearDeleteUndo() error {
	dir, err := Dir()
	if err != nil {
		return err
	}
	if err := securefile.EnsureDir(dir, 0o700); err != nil {
		return err
	}
	unlock, err := acquireSessionsLock(dir)
	if err != nil {
		return err
	}
	defer unlock()
	return clearDeleteUndoLocked(dir)
}

func deleteUndoPath(dir string) string {
	return filepath.Join(dir, deleteUndoFileName)
}

func deleteUndoStagePath(dir string) string {
	return filepath.Join(dir, deleteUndoStageFileName)
}

func clearDeleteUndoLocked(dir string) error {
	if err := removeDeleteUndoFileLocked(deleteUndoStagePath(dir)); err != nil {
		return err
	}
	return removeDeleteUndoFileLocked(deleteUndoPath(dir))
}

func removeDeleteUndoFileLocked(path string) error {
	err := securefile.RemoveFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

func loadDeleteUndoFileLocked(path string) (*DeleteUndo, []byte, error) {
	data, err := securefile.ReadFileLimited(path, maxDeleteUndoBytes)
	if err != nil {
		if errors.Is(err, securefile.ErrReadLimit) {
			return nil, nil, ErrSessionTooLarge
		}
		return nil, nil, err
	}
	var undo DeleteUndo
	if err := json.Unmarshal(data, &undo); err != nil {
		return nil, nil, err
	}
	if err := boundDeleteUndo(&undo); err != nil {
		return nil, nil, err
	}
	return &undo, data, nil
}

func marshalDeleteUndo(undo *DeleteUndo) ([]byte, *DeleteUndo, error) {
	prepared := cloneDeleteUndo(undo)
	if err := boundDeleteUndo(prepared); err != nil {
		return nil, nil, err
	}
	data, err := json.MarshalIndent(prepared, "", "  ")
	if err != nil {
		return nil, nil, err
	}
	if len(data) > maxDeleteUndoBytes {
		return nil, nil, ErrSessionTooLarge
	}
	return data, prepared, nil
}

func boundDeleteUndo(undo *DeleteUndo) error {
	if undo == nil || undo.Session == nil {
		return errors.New("delete undo is incomplete")
	}
	undo.UndoID = strings.TrimSpace(undo.UndoID)
	if undo.UndoID == "" || len(undo.UndoID) > maxDeleteUndoIDBytes || !utf8.ValidString(undo.UndoID) {
		return errors.New("delete undo id is invalid")
	}
	if !validID(undo.Session.ID) {
		return errors.New("delete undo session id is invalid")
	}
	if strings.TrimSpace(undo.Workspace) == "" || len(undo.Workspace) > maxSessionWorkspaceBytes {
		return errors.New("delete undo workspace is invalid")
	}
	if strings.TrimSpace(undo.Session.Workspace) == "" {
		return errors.New("delete undo session workspace is invalid")
	}
	if undo.ExpiresAt.IsZero() {
		return errors.New("delete undo expiry is missing")
	}
	return boundSession(undo.Session)
}

func undoSessionMissingLocked(dir, id string) (bool, error) {
	if !validID(id) {
		return false, errors.New("invalid session id")
	}
	_, err := os.Lstat(filepath.Join(dir, id+".json"))
	if err == nil {
		return false, nil
	}
	if os.IsNotExist(err) {
		return true, nil
	}
	return false, err
}

func deleteUndoExpired(undo *DeleteUndo, now time.Time) bool {
	return undo == nil || !now.Before(undo.ExpiresAt)
}

func deleteUndoIDMatches(actual, expected string) bool {
	return subtle.ConstantTimeCompare([]byte(actual), []byte(strings.TrimSpace(expected))) == 1
}

func cloneDeleteUndo(src *DeleteUndo) *DeleteUndo {
	if src == nil {
		return nil
	}
	dst := *src
	dst.Session = cloneDeleteUndoSession(src.Session)
	return &dst
}

func cloneDeleteUndoSession(src *Session) *Session {
	if src == nil {
		return nil
	}
	dst := *src
	dst.Messages = make([]llm.Message, len(src.Messages))
	for i, message := range src.Messages {
		dst.Messages[i] = message
		dst.Messages[i].Parts = append([]llm.Part(nil), message.Parts...)
		for j, part := range dst.Messages[i].Parts {
			dst.Messages[i].Parts[j].Data = append([]byte(nil), part.Data...)
		}
		dst.Messages[i].ToolCalls = append([]llm.ToolCall(nil), message.ToolCalls...)
	}
	return &dst
}
